
export const IS_LOADING_DATA_HOME = "IS_LOADING_DATA_HOME"
export const DATA_HOME = "DATA_HOME"
export const IS_LOADING_LIST_API = "IS_LOADING_LIST_API"
export const LIST_API = "LIST_API"
export const IS_LOADING_ADD_FAVORITE = "IS_LOADING_ADD_FAVORITE"
export const ADD_FAVORITE = "ADD_FAVORITE"